"""empty message

Revision ID: 96c0af1654ef
Revises: 
Create Date: 2019-08-10 18:06:27.719522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c0af1654ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('physician',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=60), nullable=False),
    sa.Column('crm', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('clinic', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clinic'], ['clinic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fullname')
    )
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('clinic', sa.Integer(), nullable=True),
    sa.Column('patient', sa.Integer(), nullable=True),
    sa.Column('physician', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['patient'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['physician'], ['physician.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_physician_patient',
    sa.Column('Physician_id', sa.Integer(), nullable=False),
    sa.Column('Patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['Physician_id'], ['physician.id'], ),
    sa.PrimaryKeyConstraint('Physician_id', 'Patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_physician_patient')
    op.drop_table('prescription')
    op.drop_table('patient')
    op.drop_table('physician')
    op.drop_table('clinic')
    # ### end Alembic commands ###
